name: Build VolVis docs
on: 
  pull_request:
    paths:
      - 'VolVis/docs/**'
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      uses: ./.github/actions/latex
      with:
        working_directory: VolVis/docs
