name: Preview LaTeX document
on: [push]
jobs:
  preview_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out latest changes
        uses: actions/checkout@v2
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: docs
          root_file: main.tex
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: Report preview
          path: docs/main.pdf          
